sudo: false
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - git submodule update --init --recursive && hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 2862b91044d4adb1ba72de1a34dc41874f282f19
  keep-history: true
  on:
    branch: master
  local-dir: public
