title: ML summaries
description: My own summaries from ML papers
author: Jorge Gomez Robles
# github: https://github.com/gomerudo
website: https://gomerudo.github.io
about: My name is Jorge and I am a Data Scientist interested in Machine Learning. The purpose of this blog is to help others to understand concepts I have struggled with.
disqus_shortname: stackproblems
# google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
#   project:
#     output: true
#     permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    - icon: fa-linkedin
      link: "http://linkedin.com/in/jgomezrb"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/gomerudo"

share:
  twitter_username: gomerudo
#   fb_appid: 1749788565247320

urls:
    - text: About The Author
      url: https://gomerudo.github.io
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /ml-summaries/feed.xml

url: "https://gomerudo.github.io"
baseurl: "/ml-summaries"
newbaseurl: "/ml-summaries"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
# gems:
plugins:
    - jekyll-paginate
    - jekyll-gist  
    - jekyll-last-modified-at
    - jekyll-figure

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
